// -------------------------------------------------------------
// 
// File Name: hdlsrc_compadder1/C_block/Subsystem2.v
// Created: 2022-05-19 12:07:45
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem2
// Source Path: C_block/Subsystem/C/Subsystem2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha4_1adder
          (A,
           B,
           C,
           D,
           Out1);


  input   [31:0] A;  // uint32
  input   [31:0] B;  // uint32
  input   [31:0] C;  // uint32
  input   [31:0] D;  // uint32
  output  [31:0] Out1;  // uint32

  wire [31:0] sum0;  // uint32
  wire [31:0] carry0;  // uint32

  // cmp4 cmp0 (A, B, C, D, carry0, sum0);
  //assign Out1 = sum0[31:0] + {carry0[30:0], 1'b0};
 


 assign sum0 = A + B ;
 assign carry0 = sum0 + C ;
 assign Out1 = carry0 + D;

  
 

endmodule  // Subsystem2

