// -------------------------------------------------------------
// 
// File Name: hdlsrc/expander_power_opt/Comp_60.v
// Created: 2022-08-12 14:04:08
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Comp_60
// Source Path: expander_power_opt/Hardware/SHA2/Compressor2/Comp_60
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Comp_60
          (clk,
           W3,
           K3,
           A_IN,
           E_IN,
           F_IN,
           G_IN,
           H_OUT,
           E_OUT,
           F_OUT,
           G_OUT,
           H_OUT_1);


  input   clk;
  input   [31:0] W3;  // uint32
  input   [31:0] K3;  // uint32
  input   [31:0] A_IN;  // uint32
  input   [31:0] E_IN;  // uint32
  input   [31:0] F_IN;  // uint32
  input   [31:0] G_IN;  // uint32
  input   [31:0] H_OUT;  // uint32
  output  [31:0] E_OUT;  // uint32
  output  [31:0] F_OUT;  // uint32
  output  [31:0] G_OUT;  // uint32
  output  [31:0] H_OUT_1;  // uint32


  reg [31:0] E_IN_REG_out1;  // uint32
  wire [31:0] SIGMA1_out1;  // uint32
  reg [31:0] F_IN_REG_out1;  // uint32
  reg [31:0] G_IN_REG_out1;  // uint32
  wire [31:0] CH_out1;  // uint32
  reg [31:0] H_IN_REG1_out1;  // uint32
  wire [31:0] Subsystem3_out1;  // uint32
  reg [31:0] A_IN_REG_out1;  // uint32
  wire [31:0] Subsystem2_out1;  // uint32


  always @(*)
 // if(clk == 1'b1)
 // begin
    begin : E_IN_REG_process
      E_IN_REG_out1 <= E_IN;
    end
 // end



  SIGMA1 u_SIGMA1 (.X(E_IN_REG_out1),  // uint32
                            .OUT(SIGMA1_out1)  // uint32
                            );

  always @(*)
//  if(clk == 1'b1)
//  begin
    begin : F_IN_REG_process
      F_IN_REG_out1 <= F_IN;
    end
 // end



  always @(*)
//  if(clk == 1'b1)
//  begin
    begin : G_IN_REG_process
      G_IN_REG_out1 <= G_IN;
    end
//  end



  CH u_CH (.X(E_IN_REG_out1),  // uint32
                    .Y(F_IN_REG_out1),  // uint32
                    .Z(G_IN_REG_out1),  // uint32
                    .OUT(CH_out1)  // uint32
                    );

  always @(*)
 // if(clk == 1'b1)
//  begin
    begin : H_IN_REG1_process
      H_IN_REG1_out1 <= H_OUT;
    end
 // end



  alpha3_1adder  u_Subsystem3 (SIGMA1_out1,  // uint32
                                    CH_out1,  // uint32
                                    H_IN_REG1_out1,  // uint32
                                    Subsystem3_out1  // uint32
                                    );

  assign E_OUT = Subsystem3_out1;

  assign F_OUT = E_IN_REG_out1;

  assign G_OUT = F_IN_REG_out1;

  always @(*)
//  if(clk == 1'b1)
 // begin
    begin : A_IN_REG_process
      A_IN_REG_out1 <= A_IN;
    end
//  end


 alpha4_1adder u_Subsystem2 (.A(W3),  // uint32
                                    .B(G_IN_REG_out1),  // uint32
                                    .C(A_IN_REG_out1),  // uint32
                                    .D(K3),  // uint32
                                    .Out1(Subsystem2_out1)  // uint32
                                    );

  assign H_OUT_1 = Subsystem2_out1;

endmodule  // Comp_60

