// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp1_32.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_32
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/Exp1_32
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_32
          (clk,
           In1,
           In2,
           In3,
           In4,
           In5,
           In6,
           In7,
           In8,
           In9,
           In10,
           In11,
           In12,
           In13,
           In14,
           In15,
           In16,
           Out1,
           Out2,
           Out3,
           Out4,
           Out5,
           Out6,
           Out7,
           Out8,
           Out9,
           Out10,
           Out11,
           Out12,
           Out13,
           Out14,
           Out15,
           Out16);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  input   [31:0] In5;  // uint32
  input   [31:0] In6;  // uint32
  input   [31:0] In7;  // uint32
  input   [31:0] In8;  // uint32
  input   [31:0] In9;  // uint32
  input   [31:0] In10;  // uint32
  input   [31:0] In11;  // uint32
  input   [31:0] In12;  // uint32
  input   [31:0] In13;  // uint32
  input   [31:0] In14;  // uint32
  input   [31:0] In15;  // uint32
  input   [31:0] In16;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32
  output  [31:0] Out5;  // uint32
  output  [31:0] Out6;  // uint32
  output  [31:0] Out7;  // uint32
  output  [31:0] Out8;  // uint32
  output  [31:0] Out9;  // uint32
  output  [31:0] Out10;  // uint32
  output  [31:0] Out11;  // uint32
  output  [31:0] Out12;  // uint32
  output  [31:0] Out13;  // uint32
  output  [31:0] Out14;  // uint32
  output  [31:0] Out15;  // uint32
  output  [31:0] Out16;  // uint32


  reg [31:0] Delay9_out1;  // uint32
  reg [31:0] Delay8_out1;  // uint32
  reg [31:0] Delay2_out1;  // uint32
  reg [31:0] Delay1_out1;  // uint32
  reg [31:0] Delay4_out1;  // uint32
  reg [31:0] Delay3_out1;  // uint32
  reg [31:0] Delay5_out1;  // uint32
  reg [31:0] Delay6_out1;  // uint32
  reg [31:0] Delay7_out1;  // uint32
  reg [31:0] Delay12_out1;  // uint32
  reg [31:0] Delay13_out1;  // uint32
  reg [31:0] Delay14_out1;  // uint32
  reg [31:0] Delay15_out1;  // uint32
  reg [31:0] Delay16_out1;  // uint32


  assign Out1 = In1;

  assign Out2 = In2;


  
 latch u_latch_1(.clk(clk),.In(In3),.Out(Out3));
 latch u_latch_2(.clk(clk),.In(In4),.Out(Out4));
 latch u_latch_3(.clk(clk),.In(In5),.Out(Out5));
 latch u_latch_4(.clk(clk),.In(In10),.Out(Out10));
 latch u_latch_5(.clk(clk),.In(In11),.Out(Out11));
 latch u_latch_6(.clk(clk),.In(In12),.Out(Out12));
 latch u_latch_7(.clk(clk),.In(In15),.Out(Out15));
 latch u_latch_8(.clk(clk),.In(In16),.Out(Out16));


  
  
 //latch_inv u_latch2 (.clk(clk),.In(In5),.Out(Out5));
 latch_inv u_latch3 (.clk(clk),.In(In6),.Out(Out6));
 //latch_inv u_latch4 (.clk(clk),.In(In4),.Out(Out4));
 latch_inv u_latch5 (.clk(clk),.In(In7),.Out(Out7));
 latch_inv u_latch6 (.clk(clk),.In(In8),.Out(Out8));
 latch_inv u_latch7 (.clk(clk),.In(In9),.Out(Out9));
 latch_inv u_latch8 (.clk(clk),.In(In14),.Out(Out14));
// latch_inv u_latch9 (.clk(clk),.In(In12),.Out(Out12));
 latch_inv u_latch10 (.clk(clk),.In(In13),.Out(Out13));




endmodule  // Exp1_32

