// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp1_63.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_63
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/Exp1_63
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_63
          (clk,
           In1,
           In2,
           Out1,
           Out2);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;
reg [31:0] Delay_out1;  // uint32

   parameter I1 =0 ;
 
if (I1 == 0) begin
 latch u_latch_1(.clk(clk),.In(In1),.Out(Out1));
   end
 else begin
 	 latch_inv u_latch1 (.clk(clk),.In(In1),.Out(Out1));
 end 


    latch_inv u_latch2 (.clk(clk),.In(In2),.Out(Out2));







endmodule  // Exp1_63

