// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp1_22.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_22
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/Exp1_22
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_22
          (clk,
           In1,
           In2,
           In3,
           In4,
           In5,
           In6,
           Out1,
           Out2,
           Out3,
           Out4,
           Out5,
           Out6);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  input   [31:0] In5;  // uint32
  input   [31:0] In6;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32
  output  [31:0] Out5;  // uint32
  output  [31:0] Out6;  // uint32


  reg [31:0] Delay9_out1;  // uint32
  reg [31:0] Delay8_out1;  // uint32
  reg [31:0] Delay3_out1;  // uint32
  reg [31:0] Delay2_out1;  // uint32


  assign Out1 = In1;

  assign Out2 = In2;

 latch_inv u_latch1 (.clk(clk),.In(In3),.Out(Out3));


 latch u_latch_1(.clk(clk),.In(In5),.Out(Out5));
 latch u_latch_2(.clk(clk),.In(In6),.Out(Out6));


  assign Out4 = In4;

 
endmodule  // Exp1_22

