// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp2_62.v
// Created: 2022-08-02 16:53:01
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp2_62
// Source Path: sha_64_unroll/Hardware/SHA2/Expander2/Exp2_62
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp2_62
          (clk,
           In1,
           Out1);


  input   clk;
  input   [31:0] In1;  // uint32
  output  [31:0] Out1;  // uint32

latch_inv u_latch1 (.clk(clk),.In(In1),.Out(Out1));
 
endmodule  // Exp2_62

