// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Hardware.v
// Created: 2022-08-02 16:53:01
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.5
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Hardware
// Source Path: sha_64_unroll/Hardware
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Hardware
          (clk,
	   clk1,
	   clk2,
	   clk3,
	   clk4,clkw_p1,clkm_p1,
           reset,
           nonce,
           Out1,
           Out2);


  input   clk,clk1,clk2,clk3,clk4,clkw_p1,clkm_p1;
  input   reset;
  input   [31:0] nonce;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32


  wire [31:0] SHA1_out1_0;  // uint32
  wire [31:0] SHA1_out1_1;  // uint32
  wire [31:0] SHA1_out1_2;  // uint32
  wire [31:0] SHA1_out1_3;  // uint32
  wire [31:0] SHA1_out1_4;  // uint32
  wire [31:0] SHA1_out1_5;  // uint32
  wire [31:0] SHA1_out1_6;  // uint32
  wire [31:0] SHA1_out1_7;  // uint32
  wire [31:0] SHA2_out1;  // uint32
  wire [31:0] SHA2_out2;  // uint32

 wire  [31:0] W1 = 32'hdc141787;  // uint32
 wire  [31:0] W2 = 32'h358b0553;  // uint32
 wire  [31:0] W3 = 32'h535f0119;  // uint32
 wire  [31:0] H0 = 32'hdc6a3b8d;  // uint32
 wire  [31:0] H1 = 32'h0c69421a;  // uint32
 wire  [31:0] H2 = 32'hcb1a5434;  // uint32
 wire  [31:0] H3 = 32'he536f7d5;  // uint32
 wire  [31:0] H4 = 32'hc3c1b9e4;  // uint32
 wire  [31:0] H5 = 32'h4cbb9b8f;  // uint32
 wire  [31:0] H6 = 32'h95f0172e;  // uint32
 wire  [31:0] H7 = 32'hfc48d2df;  // uint32

  SHA1 u_SHA1 (.clk1(clk1),
		.clk2(clk2),
		.clk3(clk3),
		.clk4(clk4),
                .clkw_p1(clkw_p1),
                .clk_l(1'b0),
                .clkm_p1(clkm_p1),
		.reset(reset),
               .Input_rsvd(W1),  // uint32
               .Input1(W2),  // uint32
               .Input2(W3),  // uint32
               .nonce(nonce),
               .H0(H0),  // uint32
               .H1(H1),  // uint32
               .H2(H2),  // uint32
               .H3(H3),  // uint32
               .H4(H4),  // uint32
               .H5(H5),  // uint32
               .H6(H6),  // uint32
               .H7(H7),  // uint32
               .Out1_0(SHA1_out1_0),  // uint32
               .Out1_1(SHA1_out1_1),  // uint32
               .Out1_2(SHA1_out1_2),  // uint32
               .Out1_3(SHA1_out1_3),  // uint32
               .Out1_4(SHA1_out1_4),  // uint32
               .Out1_5(SHA1_out1_5),  // uint32
               .Out1_6(SHA1_out1_6),  // uint32
               .Out1_7(SHA1_out1_7)  // uint32
               );

  SHA2 u_SHA2 (.clk1(clk1),
		.clk2(clk2),
		.clk3(clk3),
		.clk4(clk4),
		.resetn(reset),
               .In1_0(SHA1_out1_0),  // uint32
               .In1_1(SHA1_out1_1),  // uint32
               .In1_2(SHA1_out1_2),  // uint32
               .In1_3(SHA1_out1_3),  // uint32
               .In1_4(SHA1_out1_4),  // uint32
               .In1_5(SHA1_out1_5),  // uint32
               .In1_6(SHA1_out1_6),  // uint32
               .In1_7(SHA1_out1_7),  // uint32
               .Out1(SHA2_out1),  // uint32
               .Out2(SHA2_out2)  // uint32
               );

  assign Out1 = ~SHA2_out1;

  assign Out2 = ~SHA2_out2;

endmodule  // Hardware

