// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/SHA1.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SHA1
// Source Path: sha_64_unroll/Hardware/SHA1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SHA1
          (clk1,
	   clk2,
	   clk3,
	   clk4,clkw_p1,clk_l,clkm_p1,
           reset,
           Input_rsvd,
           Input1,
           Input2,nonce,
           H0,
           H1,
           H2,
           H3,
           H4,
           H5,
           H6,
           H7,
           Out1_0,
           Out1_1,
           Out1_2,
           Out1_3,
           Out1_4,
           Out1_5,
           Out1_6,
           Out1_7);


  input   clk1,clk2,clk3,clk4,clkw_p1,clk_l,clkm_p1;
  input   reset;
  input   [31:0] Input_rsvd;  // uint32
  input   [31:0] Input1;  // uint32
  input   [31:0] Input2,nonce;  // uint32
  input   [31:0] H0;  // uint32
  input   [31:0] H1;  // uint32
  input   [31:0] H2;  // uint32
  input   [31:0] H3;  // uint32
  input   [31:0] H4;  // uint32
  input   [31:0] H5;  // uint32
  input   [31:0] H6;  // uint32
  input   [31:0] H7;  // uint32
  output  [31:0] Out1_0;  // uint32
  output  [31:0] Out1_1;  // uint32
  output  [31:0] Out1_2;  // uint32
  output  [31:0] Out1_3;  // uint32
  output  [31:0] Out1_4;  // uint32
  output  [31:0] Out1_5;  // uint32
  output  [31:0] Out1_6;  // uint32
  output  [31:0] Out1_7;  // uint32


  wire [31:0] Expander1_out1;  // uint32
  wire [31:0] Expander1_out2;  // uint32
  wire [31:0] Expander1_out3;  // uint32
  wire [31:0] Expander1_out4;  // uint32
  wire [31:0] Expander1_out5;  // uint32
  wire [31:0] Expander1_out6;  // uint32
  wire [31:0] Expander1_out7;  // uint32
  wire [31:0] Expander1_out8;  // uint32
  wire [31:0] Expander1_out9;  // uint32
  wire [31:0] Expander1_out10;  // uint32
  wire [31:0] Expander1_out11;  // uint32
  wire [31:0] Expander1_out12;  // uint32
  wire [31:0] Expander1_out13;  // uint32
  wire [31:0] Expander1_out14;  // uint32
  wire [31:0] Expander1_out15;  // uint32
  wire [31:0] Expander1_out16;  // uint32
  wire [31:0] Expander1_out17;  // uint32
  wire [31:0] Expander1_out18;  // uint32
  wire [31:0] Expander1_out19;  // uint32
  wire [31:0] Expander1_out20;  // uint32
  wire [31:0] Expander1_out21;  // uint32
  wire [31:0] Expander1_out22;  // uint32
  wire [31:0] Expander1_out23;  // uint32
  wire [31:0] Expander1_out24;  // uint32
  wire [31:0] Expander1_out25;  // uint32
  wire [31:0] Expander1_out26;  // uint32
  wire [31:0] Expander1_out27;  // uint32
  wire [31:0] Expander1_out28;  // uint32
  wire [31:0] Expander1_out29;  // uint32
  wire [31:0] Expander1_out30;  // uint32
  wire [31:0] Expander1_out31;  // uint32
  wire [31:0] Expander1_out32;  // uint32
  wire [31:0] Expander1_out33;  // uint32
  wire [31:0] Expander1_out34;  // uint32
  wire [31:0] Expander1_out35;  // uint32
  wire [31:0] Expander1_out36;  // uint32
  wire [31:0] Expander1_out37;  // uint32
  wire [31:0] Expander1_out38;  // uint32
  wire [31:0] Expander1_out39;  // uint32
  wire [31:0] Expander1_out40;  // uint32
  wire [31:0] Expander1_out41;  // uint32
  wire [31:0] Expander1_out42;  // uint32
  wire [31:0] Expander1_out43;  // uint32
  wire [31:0] Expander1_out44;  // uint32
  wire [31:0] Expander1_out45;  // uint32
  wire [31:0] Expander1_out46;  // uint32
  wire [31:0] Expander1_out47;  // uint32
  wire [31:0] Expander1_out48;  // uint32
  wire [31:0] Expander1_out49;  // uint32
  wire [31:0] Expander1_out50;  // uint32
  wire [31:0] Expander1_out51;  // uint32
  wire [31:0] Expander1_out52;  // uint32
  wire [31:0] Expander1_out53;  // uint32
  wire [31:0] Expander1_out54;  // uint32
  wire [31:0] Expander1_out55;  // uint32
  wire [31:0] Expander1_out56;  // uint32
  wire [31:0] Expander1_out57;  // uint32
  wire [31:0] Expander1_out58;  // uint32
  wire [31:0] Expander1_out59;  // uint32
  wire [31:0] Expander1_out60;  // uint32
  wire [31:0] Expander1_out61;  // uint32
  wire [31:0] Expander1_out62;  // uint32
  wire [31:0] Expander1_out63;  // uint32
  wire [31:0] Expander1_out64;  // uint32
  wire [31:0] Compressor1_out1_0;  // uint32
  wire [31:0] Compressor1_out1_1;  // uint32
  wire [31:0] Compressor1_out1_2;  // uint32
  wire [31:0] Compressor1_out1_3;  // uint32
  wire [31:0] Compressor1_out1_4;  // uint32
  wire [31:0] Compressor1_out1_5;  // uint32
  wire [31:0] Compressor1_out1_6;  // uint32
  wire [31:0] Compressor1_out1_7;  // uint32


  Expander1 u_Expander1 (.clk1(clk1),
			.clk2(clk2),
			.clk3(clk3),
			.clk4(clk4),
                        .clkw_p1(clkw_p1), 
			.reset(reset),
                         .W1(Input_rsvd),  // uint32
                         .W2(Input1),  // uint32
                         .W3(Input2),  // uint32
			 .nonce(nonce),
                         .Out1(Expander1_out1),  // uint32
                         .Out2(Expander1_out2),  // uint32
                         .Out3(Expander1_out3),  // uint32
                         .W4(Expander1_out4),  // uint32
                         .W5(Expander1_out5),  // uint32
                         .W6(Expander1_out6),  // uint32
                         .W7(Expander1_out7),  // uint32
                         .W8(Expander1_out8),  // uint32
                         .W9(Expander1_out9),  // uint32
                         .W10(Expander1_out10),  // uint32
                         .W11(Expander1_out11),  // uint32
                         .W12(Expander1_out12),  // uint32
                         .W13(Expander1_out13),  // uint32
                         .W14(Expander1_out14),  // uint32
                         .W15(Expander1_out15),  // uint32
                         .W16(Expander1_out16),  // uint32
                         .W17(Expander1_out17),  // uint32
                         .W18(Expander1_out18),  // uint32
                         .W19(Expander1_out19),  // uint32
                         .W20(Expander1_out20),  // uint32
                         .W21(Expander1_out21),  // uint32
                         .W22(Expander1_out22),  // uint32
                         .W23(Expander1_out23),  // uint32
                         .W24(Expander1_out24),  // uint32
                         .W25(Expander1_out25),  // uint32
                         .W26(Expander1_out26),  // uint32
                         .W27(Expander1_out27),  // uint32
                         .W28(Expander1_out28),  // uint32
                         .W29(Expander1_out29),  // uint32
                         .W30(Expander1_out30),  // uint32
                         .W31(Expander1_out31),  // uint32
                         .W32(Expander1_out32),  // uint32
                         .W33(Expander1_out33),  // uint32
                         .W34(Expander1_out34),  // uint32
                         .W35(Expander1_out35),  // uint32
                         .W36(Expander1_out36),  // uint32
                         .W37(Expander1_out37),  // uint32
                         .W38(Expander1_out38),  // uint32
                         .W39(Expander1_out39),  // uint32
                         .W40(Expander1_out40),  // uint32
                         .W41(Expander1_out41),  // uint32
                         .W42(Expander1_out42),  // uint32
                         .W43(Expander1_out43),  // uint32
                         .W44(Expander1_out44),  // uint32
                         .W45(Expander1_out45),  // uint32
                         .W46(Expander1_out46),  // uint32
                         .W47(Expander1_out47),  // uint32
                         .W48(Expander1_out48),  // uint32
                         .W49(Expander1_out49),  // uint32
                         .W50(Expander1_out50),  // uint32
                         .W51(Expander1_out51),  // uint32
                         .W52(Expander1_out52),  // uint32
                         .W53(Expander1_out53),  // uint32
                         .W54(Expander1_out54),  // uint32
                         .W55(Expander1_out55),  // uint32
                         .W56(Expander1_out56),  // uint32
                         .W57(Expander1_out57),  // uint32
                         .W58(Expander1_out58),  // uint32
                         .W59(Expander1_out59),  // uint32
                         .W60(Expander1_out60),  // uint32
                         .W61(Expander1_out61),  // uint32
                         .W62(Expander1_out62),  // uint32
                         .W63(Expander1_out63),  // uint32
                         .W64(Expander1_out64)  // uint32
                         );

  Compressor1 u_Compressor1 (.clk1(clk1),
				.clk2(clk2),
				.clk3(clk3),
				.clk4(clk4),
			        .clk_l(clk_l),	
                                .clkm_p1(clkm_p1),     
				.resetn(reset),
			     .W1(Expander1_out1),  // uint32
			     .W2(Expander1_out2),  // uint32
                             .W3(Expander1_out3),  // uint32
                             .W4(Expander1_out4),  // uint32
                             .W5(Expander1_out5),  // uint32
                             .W6(Expander1_out6),  // uint32
                             .W7(Expander1_out7),  // uint32
                             .W8(Expander1_out8),  // uint32
                             .W9(Expander1_out9),  // uint32
                             .W10(Expander1_out10),  // uint32
                             .W11(Expander1_out11),  // uint32
                             .W12(Expander1_out12),  // uint32
                             .W13(Expander1_out13),  // uint32
                             .W14(Expander1_out14),  // uint32
                             .W15(Expander1_out15),  // uint32
                             .W16(Expander1_out16),  // uint32
                             .W17(Expander1_out17),  // uint32
                             .W18(Expander1_out18),  // uint32
                             .W19(Expander1_out19),  // uint32
                             .W20(Expander1_out20),  // uint32
                             .W21(Expander1_out21),  // uint32
                             .W22(Expander1_out22),  // uint32
                             .W23(Expander1_out23),  // uint32
                             .W24(Expander1_out24),  // uint32
                             .W25(Expander1_out25),  // uint32
                             .W26(Expander1_out26),  // uint32
                             .W27(Expander1_out27),  // uint32
                             .W28(Expander1_out28),  // uint32
                             .W29(Expander1_out29),  // uint32
                             .W30(Expander1_out30),  // uint32
                             .W31(Expander1_out31),  // uint32
                             .W32(Expander1_out32),  // uint32
                             .W33(Expander1_out33),  // uint32
                             .W34(Expander1_out34),  // uint32
                             .W35(Expander1_out35),  // uint32
                             .W36(Expander1_out36),  // uint32
                             .W37(Expander1_out37),  // uint32
                             .W38(Expander1_out38),  // uint32
                             .W39(Expander1_out39),  // uint32
                             .W40(Expander1_out40),  // uint32
                             .W41(Expander1_out41),  // uint32
                             .W42(Expander1_out42),  // uint32
                             .W43(Expander1_out43),  // uint32
                             .W44(Expander1_out44),  // uint32
                             .W45(Expander1_out45),  // uint32
                             .W46(Expander1_out46),  // uint32
                             .W47(Expander1_out47),  // uint32
                             .W48(Expander1_out48),  // uint32
                             .W49(Expander1_out49),  // uint32
                             .W50(Expander1_out50),  // uint32
                             .W51(Expander1_out51),  // uint32
                             .W52(Expander1_out52),  // uint32
                             .W53(Expander1_out53),  // uint32
                             .W54(Expander1_out54),  // uint32
                             .W55(Expander1_out55),  // uint32
                             .W56(Expander1_out56),  // uint32
                             .W57(Expander1_out57),  // uint32
                             .W58(Expander1_out58),  // uint32
                             .W59(Expander1_out59),  // uint32
                             .W60(Expander1_out60),  // uint32
                             .W61(Expander1_out61),  // uint32
                             .W62(Expander1_out62),  // uint32
                             .W63(Expander1_out63),  // uint32
                             .W64(Expander1_out64),  // uint32
                             .H0(H0),  // uint32
                             .H1(H1),  // uint32
                             .H2(H2),  // uint32
                             .H3(H3),  // uint32
                             .H4(H4),  // uint32
                             .H5(H5),  // uint32
                             .H6(H6),  // uint32
                             .H7(H7),  // uint32
                             .Out1_0(Compressor1_out1_0),  // uint32
                             .Out1_1(Compressor1_out1_1),  // uint32
                             .Out1_2(Compressor1_out1_2),  // uint32
                             .Out1_3(Compressor1_out1_3),  // uint32
                             .Out1_4(Compressor1_out1_4),  // uint32
                             .Out1_5(Compressor1_out1_5),  // uint32
                             .Out1_6(Compressor1_out1_6),  // uint32
                             .Out1_7(Compressor1_out1_7)  // uint32
                             );

  assign Out1_0 = Compressor1_out1_0;

  assign Out1_1 = Compressor1_out1_1;

  assign Out1_2 = Compressor1_out1_2;

  assign Out1_3 = Compressor1_out1_3;

  assign Out1_4 = Compressor1_out1_4;

  assign Out1_5 = Compressor1_out1_5;

  assign Out1_6 = Compressor1_out1_6;

  assign Out1_7 = Compressor1_out1_7;

endmodule  // SHA1

