// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/SHA2.v
// Created: 2022-08-02 16:53:01
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SHA2
// Source Path: sha_64_unroll/Hardware/SHA2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SHA2
          (clk1,
	   clk2,
	   clk3,
	   clk4,
	   resetn,
           In1_0,
           In1_1,
           In1_2,
           In1_3,
           In1_4,
           In1_5,
           In1_6,
           In1_7,
           Out1,
           Out2);


  input   clk1,clk2,clk3,clk4,resetn;
  input   [31:0] In1_0;  // uint32
  input   [31:0] In1_1;  // uint32
  input   [31:0] In1_2;  // uint32
  input   [31:0] In1_3;  // uint32
  input   [31:0] In1_4;  // uint32
  input   [31:0] In1_5;  // uint32
  input   [31:0] In1_6;  // uint32
  input   [31:0] In1_7;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32


  wire [31:0] Expander2_out1;  // uint32
  wire [31:0] Expander2_out2;  // uint32
  wire [31:0] Expander2_out3;  // uint32
  wire [31:0] Expander2_out4;  // uint32
  wire [31:0] Expander2_out5;  // uint32
  wire [31:0] Expander2_out6;  // uint32
  wire [31:0] Expander2_out7;  // uint32
  wire [31:0] Expander2_out8;  // uint32
  wire [31:0] Expander2_out9;  // uint32
  wire [31:0] Expander2_out10;  // uint32
  wire [31:0] Expander2_out11;  // uint32
  wire [31:0] Expander2_out12;  // uint32
  wire [31:0] Expander2_out13;  // uint32
  wire [31:0] Expander2_out14;  // uint32
  wire [31:0] Expander2_out15;  // uint32
  wire [31:0] Expander2_out16;  // uint32
  wire [31:0] Expander2_out17;  // uint32
  wire [31:0] Expander2_out18;  // uint32
  wire [31:0] Expander2_out19;  // uint32
  wire [31:0] Expander2_out20;  // uint32
  wire [31:0] Expander2_out21;  // uint32
  wire [31:0] Expander2_out22;  // uint32
  wire [31:0] Expander2_out23;  // uint32
  wire [31:0] Expander2_out24;  // uint32
  wire [31:0] Expander2_out25;  // uint32
  wire [31:0] Expander2_out26;  // uint32
  wire [31:0] Expander2_out27;  // uint32
  wire [31:0] Expander2_out28;  // uint32
  wire [31:0] Expander2_out29;  // uint32
  wire [31:0] Expander2_out30;  // uint32
  wire [31:0] Expander2_out31;  // uint32
  wire [31:0] Expander2_out32;  // uint32
  wire [31:0] Expander2_out33;  // uint32
  wire [31:0] Expander2_out34;  // uint32
  wire [31:0] Expander2_out35;  // uint32
  wire [31:0] Expander2_out36;  // uint32
  wire [31:0] Expander2_out37;  // uint32
  wire [31:0] Expander2_out38;  // uint32
  wire [31:0] Expander2_out39;  // uint32
  wire [31:0] Expander2_out40;  // uint32
  wire [31:0] Expander2_out41;  // uint32
  wire [31:0] Expander2_out42;  // uint32
  wire [31:0] Expander2_out43;  // uint32
  wire [31:0] Expander2_out44;  // uint32
  wire [31:0] Expander2_out45;  // uint32
  wire [31:0] Expander2_out46;  // uint32
  wire [31:0] Expander2_out47;  // uint32
  wire [31:0] Expander2_out48;  // uint32
  wire [31:0] Expander2_out49;  // uint32
  wire [31:0] Expander2_out50;  // uint32
  wire [31:0] Expander2_out51;  // uint32
  wire [31:0] Expander2_out52;  // uint32
  wire [31:0] Expander2_out53;  // uint32
  wire [31:0] Expander2_out54;  // uint32
  wire [31:0] Expander2_out55;  // uint32
  wire [31:0] Expander2_out56;  // uint32
  wire [31:0] Expander2_out57;  // uint32
  wire [31:0] Expander2_out58;  // uint32
  wire [31:0] Expander2_out59;  // uint32
  wire [31:0] Expander2_out60;  // uint32
  wire [31:0] Expander2_out61;  // uint32
  wire [31:0] Expander2_out62;  // uint32
  wire [31:0] Constant4_out1;  // uint32
  wire [31:0] Constant5_out1;  // uint32
  wire [31:0] Constant6_out1;  // uint32
  wire [31:0] Constant7_out1;  // uint32
  wire [31:0] Constant8_out1;  // uint32
  wire [31:0] Constant69_out1;  // uint32
  wire [31:0] Constant14_out1;  // uint32
  wire [31:0] Constant_out1;  // uint32
  wire [31:0] Compressor2_out1;  // uint32
  wire [31:0] Compressor2_out2;  // uint32


  Expander2 u_Expander2 (.clk1(clk1),
		.clk2(clk2),
		.clk3(clk3),
		.clk4(clk4),
                         .In1_0(In1_0),  // uint32
                         .In1_1(In1_1),  // uint32
                         .In1_2(In1_2),  // uint32
                         .In1_3(In1_3),  // uint32
                         .In1_4(In1_4),  // uint32
                         .In1_5(In1_5),  // uint32
                         .In1_6(In1_6),  // uint32
                         .In1_7(In1_7),  // uint32
                         .Out1(Expander2_out1),  // uint32
                         .Out2(Expander2_out2),  // uint32
                         .Out3(Expander2_out3),  // uint32
                         .Out4(Expander2_out4),  // uint32
                         .Out5(Expander2_out5),  // uint32
                         .Out6(Expander2_out6),  // uint32
                         .Out7(Expander2_out7),  // uint32
                         .Out8(Expander2_out8),  // uint32
                         .Out9(Expander2_out9),  // uint32
                         .Out10(Expander2_out10),  // uint32
                         .Out11(Expander2_out11),  // uint32
                         .Out12(Expander2_out12),  // uint32
                         .Out13(Expander2_out13),  // uint32
                         .Out14(Expander2_out14),  // uint32
                         .Out15(Expander2_out15),  // uint32
                         .Out16(Expander2_out16),  // uint32
                         .Out17(Expander2_out17),  // uint32
                         .Out18(Expander2_out18),  // uint32
                         .Out19(Expander2_out19),  // uint32
                         .Out20(Expander2_out20),  // uint32
                         .Out21(Expander2_out21),  // uint32
                         .Out22(Expander2_out22),  // uint32
                         .Out23(Expander2_out23),  // uint32
                         .Out24(Expander2_out24),  // uint32
                         .Out25(Expander2_out25),  // uint32
                         .Out26(Expander2_out26),  // uint32
                         .Out27(Expander2_out27),  // uint32
                         .Out28(Expander2_out28),  // uint32
                         .Out29(Expander2_out29),  // uint32
                         .Out30(Expander2_out30),  // uint32
                         .Out31(Expander2_out31),  // uint32
                         .Out32(Expander2_out32),  // uint32
                         .Out33(Expander2_out33),  // uint32
                         .Out34(Expander2_out34),  // uint32
                         .Out35(Expander2_out35),  // uint32
                         .Out36(Expander2_out36),  // uint32
                         .Out37(Expander2_out37),  // uint32
                         .Out38(Expander2_out38),  // uint32
                         .Out39(Expander2_out39),  // uint32
                         .Out40(Expander2_out40),  // uint32
                         .Out41(Expander2_out41),  // uint32
                         .Out42(Expander2_out42),  // uint32
                         .Out43(Expander2_out43),  // uint32
                         .Out44(Expander2_out44),  // uint32
                         .Out45(Expander2_out45),  // uint32
                         .Out46(Expander2_out46),  // uint32
                         .Out47(Expander2_out47),  // uint32
                         .Out48(Expander2_out48),  // uint32
                         .Out49(Expander2_out49),  // uint32
                         .Out50(Expander2_out50),  // uint32
                         .Out51(Expander2_out51),  // uint32
                         .Out52(Expander2_out52),  // uint32
                         .Out53(Expander2_out53),  // uint32
                         .Out54(Expander2_out54),  // uint32
                         .Out55(Expander2_out55),  // uint32
                         .Out56(Expander2_out56),  // uint32
                         .Out57(Expander2_out57),  // uint32
                         .Out58(Expander2_out58),  // uint32
                         .Out59(Expander2_out59),  // uint32
                         .Out60(Expander2_out60),  // uint32
                         .Out61(Expander2_out61),  // uint32
                         .Out62(Expander2_out62)  // uint32
                         );

  assign Constant4_out1 = 32'b01101010000010011110011001100111;



  assign Constant5_out1 = 32'b10111011011001111010111010000101;



  assign Constant6_out1 = 32'b00111100011011101111001101110010;



  assign Constant7_out1 = 32'b10100101010011111111010100111010;



  assign Constant8_out1 = 32'b01010001000011100101001001111111;



  assign Constant69_out1 = 32'b10011011000001010110100010001100;



  assign Constant14_out1 = 32'b00011111100000111101100110101011;



  assign Constant_out1 = 32'b01011011111000001100110100011001;



  Compressor2 u_Compressor2 (.clk1(clk1),
		.clk2(clk2),
		.clk3(clk3),
		.clk4(clk4),		
		.resetn(resetn),
                             .W1(Expander2_out1),  // uint32
                             .W2(Expander2_out2),  // uint32
                             .W3(Expander2_out3),  // uint32
                             .W4(Expander2_out4),  // uint32
                             .W5(Expander2_out5),  // uint32
                             .W6(Expander2_out6),  // uint32
                             .W7(Expander2_out7),  // uint32
                             .W8(Expander2_out8),  // uint32
                             .W9(Expander2_out9),  // uint32
                             .W10(Expander2_out10),  // uint32
                             .W11(Expander2_out11),  // uint32
                             .W12(Expander2_out12),  // uint32
                             .W13(Expander2_out13),  // uint32
                             .W14(Expander2_out14),  // uint32
                             .W15(Expander2_out15),  // uint32
                             .W16(Expander2_out16),  // uint32
                             .W17(Expander2_out17),  // uint32
                             .W18(Expander2_out18),  // uint32
                             .W19(Expander2_out19),  // uint32
                             .W20(Expander2_out20),  // uint32
                             .W21(Expander2_out21),  // uint32
                             .W22(Expander2_out22),  // uint32
                             .W23(Expander2_out23),  // uint32
                             .W24(Expander2_out24),  // uint32
                             .W25(Expander2_out25),  // uint32
                             .W26(Expander2_out26),  // uint32
                             .W27(Expander2_out27),  // uint32
                             .W28(Expander2_out28),  // uint32
                             .W29(Expander2_out29),  // uint32
                             .W30(Expander2_out30),  // uint32
                             .W31(Expander2_out31),  // uint32
                             .W32(Expander2_out32),  // uint32
                             .W33(Expander2_out33),  // uint32
                             .W34(Expander2_out34),  // uint32
                             .W35(Expander2_out35),  // uint32
                             .W36(Expander2_out36),  // uint32
                             .W37(Expander2_out37),  // uint32
                             .W38(Expander2_out38),  // uint32
                             .W39(Expander2_out39),  // uint32
                             .W40(Expander2_out40),  // uint32
                             .W41(Expander2_out41),  // uint32
                             .W42(Expander2_out42),  // uint32
                             .W43(Expander2_out43),  // uint32
                             .W44(Expander2_out44),  // uint32
                             .W45(Expander2_out45),  // uint32
                             .W46(Expander2_out46),  // uint32
                             .W47(Expander2_out47),  // uint32
                             .W48(Expander2_out48),  // uint32
                             .W49(Expander2_out49),  // uint32
                             .W50(Expander2_out50),  // uint32
                             .W51(Expander2_out51),  // uint32
                             .W52(Expander2_out52),  // uint32
                             .W53(Expander2_out53),  // uint32
                             .W54(Expander2_out54),  // uint32
                             .W55(Expander2_out55),  // uint32
                             .W56(Expander2_out56),  // uint32
                             .W57(Expander2_out57),  // uint32
                             .W58(Expander2_out58),  // uint32
                             .W59(Expander2_out59),  // uint32
                             .W60(Expander2_out60),  // uint32
                             .W61(Expander2_out61),  // uint32
                             .W62(Expander2_out62),  // uint32
                             .H0(Constant4_out1),  // uint32
                             .H1(Constant5_out1),  // uint32
                             .H2(Constant6_out1),  // uint32
                             .H3(Constant7_out1),  // uint32
                             .H4(Constant8_out1),  // uint32
                             .H5(Constant69_out1),  // uint32
                             .H6(Constant14_out1),  // uint32
                             .H7(Constant_out1),  // uint32
                             .Out2(Compressor2_out1),  // uint32  // MSB
                             .Out3(Compressor2_out2)  // uint32   // LSB
                             );

  assign Out1 = Compressor2_out1; // MSB

  assign Out2 = Compressor2_out2;  /// LSB

endmodule  // SHA2

