// -------------------------------------------------------------
// 
// File Name: hdlsrc_comp/untitled/SIGMA0.v
// Created: 2022-06-22 14:04:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SIGMA0
// Source Path: untitled/Subsystem/COMPRESSOR2/Comp1/SIGMA0
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SIGMA0
          (X,
           OUT);


  input   [31:0] X;  // uint32
  output  [31:0] OUT;  // uint32


  wire [31:0] Bit_Rotate_out1;  // uint32
  wire [31:0] Bit_Rotate1_out1;  // uint32
  wire [31:0] Bit_Rotate2_out1;  // uint32
  wire [31:0] Bitwise_XOR1_out1;  // uint32

  // function out = capSigma0( x )
  //    % Function Ó0 : Performs Ó0 operation.(§4.1.2)
  //    out = bitxor( bitxor( rotr( x, 2 ), rotr( x, 13 ) ) , rotr( x, 22 ) );
  // end


  assign Bit_Rotate_out1 = {X[1:0], X[31:2]};



  assign Bit_Rotate1_out1 = {X[12:0], X[31:13]};



  assign Bit_Rotate2_out1 = {X[21:0], X[31:22]};



  assign Bitwise_XOR1_out1 = Bit_Rotate2_out1 ^ (Bit_Rotate_out1 ^ Bit_Rotate1_out1);



  assign OUT = Bitwise_XOR1_out1;

endmodule  // SIGMA0

