// -------------------------------------------------------------
// 
// File Name: hdlsrc_comp/untitled/SIGMA1.v
// Created: 2022-06-22 14:04:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SIGMA1
// Source Path: untitled/Subsystem/COMPRESSOR2/Comp1/SIGMA1
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SIGMA1
          (X,
           OUT);


  input   [31:0] X;  // uint32
  output  [31:0] OUT;  // uint32


  wire [31:0] Bit_Rotate_out1;  // uint32
  wire [31:0] Bit_Rotate1_out1;  // uint32
  wire [31:0] Bit_Rotate2_out1;  // uint32
  wire [31:0] Bitwise_XOR1_out1;  // uint32

  // function out = capSigma1( word )
  //    % Function Ó1 : Performs Ó0 operation.(§4.1.2)
  //    out = bitxor( bitxor( rotr( word, 6 ), rotr( word, 11 ) ) , rotr( word, 25 ) );
  // end


  assign Bit_Rotate_out1 = {X[5:0], X[31:6]};



  assign Bit_Rotate1_out1 = {X[10:0], X[31:11]};



  assign Bit_Rotate2_out1 = {X[24:0], X[31:25]};



  assign Bitwise_XOR1_out1 = Bit_Rotate2_out1 ^ (Bit_Rotate_out1 ^ Bit_Rotate1_out1);



  assign OUT = Bitwise_XOR1_out1;

endmodule  // SIGMA1

