// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/sigma1_block62.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sigma1_block62
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/sigma1 
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sigma1_block62
          (In3,
           Out1);


  input   [31:0] In3;  // uint32
  output  [31:0] Out1;  // uint32


  wire [31:0] Bit_Rotate2_out1;  // uint32
  wire [31:0] Bit_Rotate3_out1;  // uint32
  wire [31:0] Bit_Shift_out1;  // uint32
  wire [31:0] Bitwise_XOR_out1;  // uint32


  assign Bit_Rotate2_out1 = {In3[16:0], In3[31:17]};



  assign Bit_Rotate3_out1 = {In3[18:0], In3[31:19]};



  assign Bit_Shift_out1 = In3 >> 8'd10;



  assign Bitwise_XOR_out1 = Bit_Shift_out1 ^ (Bit_Rotate2_out1 ^ Bit_Rotate3_out1);



  assign Out1 = Bitwise_XOR_out1;

endmodule  // sigma1_block62

