// -------------------------------------------------------------
// 
// File Name: hdlsrc/expander_power_opt/Comp_initial1.v
// Created: 2022-08-12 14:04:08
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Comp_initial1
// Source Path: expander_power_opt/Hardware/SHA2/Compressor2/Comp_initial1
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Comp_initial1
          (W,
           W_i_1,
           A_IN,
           B_IN,
           C_IN,
           D_IN,
           E_IN,
           F_IN,
           A_OUT,
           B_OUT,
           C_OUT,
           D_OUT,
           E_OUT,
           F_OUT,
           G_OUT,
           H_OUT_1);


  input   [31:0] W;  // uint32
  input   [31:0] W_i_1;  // uint32
  input   [31:0] A_IN;  // uint32
  input   [31:0] B_IN;  // uint32
  input   [31:0] C_IN;  // uint32
  input   [31:0] D_IN;  // uint32
  input   [31:0] E_IN;  // uint32
  input   [31:0] F_IN;  // uint32
  output  [31:0] A_OUT;  // uint32
  output  [31:0] B_OUT;  // uint32
  output  [31:0] C_OUT;  // uint32
  output  [31:0] D_OUT;  // uint32
  output  [31:0] E_OUT;  // uint32
  output  [31:0] F_OUT;  // uint32
  output  [31:0] G_OUT;  // uint32
  output  [31:0] H_OUT_1;  // uint32


  wire [31:0] Constant_out1;  // uint32
  wire [31:0] ADD1_out1;  // uint32
  wire [31:0] Constant1_out1;  // uint32
  wire [31:0] ADD8_out1;  // uint32


  assign A_OUT = A_IN;

  assign B_OUT = B_IN;

  assign C_OUT = C_IN;

  assign D_OUT = D_IN;

  assign Constant_out1 = 32'b10011000110001111110001010100010;



  assign ADD1_out1 = Constant_out1 + W;



  assign E_OUT = ADD1_out1;

  assign F_OUT = E_IN;

  assign G_OUT = F_IN;

  assign Constant1_out1 = 32'b11001101001010100001000110101110;



  assign ADD8_out1 = Constant1_out1 + W_i_1;



  assign H_OUT_1 = ADD8_out1;

endmodule  // Comp_initial1

