// -------------------------------------------------------------
// 
// File Name: hdlsrc/expander_power_opt/Comp_2.v
// Created: 2022-08-12 14:04:05
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Comp_2
// Source Path: expander_power_opt/Hardware/SHA2/Compressor2/Comp_2
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Comp_2
          (clk,
           W,
           A_IN,
           B_IN,
           C_IN,
           D_IN,
           E_IN,
           F_IN,
           G_IN,
           H_OUT,
           A_OUT,
           B_OUT,
           C_OUT,
           D_OUT,
           E_OUT,
           F_OUT,
           G_OUT,
           H_OUT_1);


  input   clk;
  input   [31:0] W;  // uint32
  input   [31:0] A_IN;  // uint32
  input   [31:0] B_IN;  // uint32
  input   [31:0] C_IN;  // uint32
  input   [31:0] D_IN;  // uint32
  input   [31:0] E_IN;  // uint32
  input   [31:0] F_IN;  // uint32
  input   [31:0] G_IN;  // uint32
  input   [31:0] H_OUT;  // uint32
  output  [31:0] A_OUT;  // uint32
  output  [31:0] B_OUT;  // uint32
  output  [31:0] C_OUT;  // uint32
  output  [31:0] D_OUT;  // uint32
  output  [31:0] E_OUT;  // uint32
  output  [31:0] F_OUT;  // uint32
  output  [31:0] G_OUT;  // uint32
  output  [31:0] H_OUT_1;  // uint32


  wire [31:0] Constant_out1;  // uint32
  reg [31:0] D_IN_REG_out1;  // uint32
  wire [31:0] ADD10_out1;  // uint32
  reg [31:0] E_IN_REG_out1;  // uint32
  wire [31:0] ADD12_out1;  // uint32
  wire [31:0] SIGMA1_out1;  // uint32
  reg [31:0] F_IN_REG_out1;  // uint32
  wire [31:0] CH_out1;  // uint32
  reg [31:0] H_IN_REG1_out1;  // uint32
  wire [31:0] Subsystem3_out1;  // uint32
  wire [31:0] Constant1_out1;  // uint32
  wire [31:0] ADD14_out1;  // uint32


  assign Constant_out1 = 32'b00001000100100001001101011100101;



  always @(*)
 // if(clk == 1'b1)
 // begin
    begin : D_IN_REG_process
      D_IN_REG_out1 <= D_IN;
    end
 // end



  assign ADD10_out1 = Constant_out1 + D_IN_REG_out1;



  assign A_OUT = ADD10_out1;

  assign B_OUT = A_IN;

  assign C_OUT = B_IN;

  always @(*)
  //if(clk == 1'b1)
 // begin
    begin : E_IN_REG_process
      E_IN_REG_out1 <= E_IN;
    end
 // end



  assign ADD12_out1 = E_IN_REG_out1 - C_IN;



  assign D_OUT = ADD12_out1;

  SIGMA1 u_SIGMA1 (.X(E_IN_REG_out1),  // uint32
                           .OUT(SIGMA1_out1)  // uint32
                           );

  always @(*)
 // if(clk == 1'b1)
//  begin
    begin : F_IN_REG_process
      F_IN_REG_out1 <= F_IN;
    end
//  end



  CH u_CH (.X(E_IN_REG_out1),  // uint32
                   .Y(F_IN_REG_out1),  // uint32
                   .Z(G_IN),  // uint32
                   .OUT(CH_out1)  // uint32
                   );

  always @(*)
 // if(clk == 1'b1)
 // begin
    begin : H_IN_REG1_process
      H_IN_REG1_out1 <= H_OUT;
    end
 // end



  alpha3_1adder u_Subsystem3 (SIGMA1_out1,  // uint32
                                   CH_out1,  // uint32
                                   H_IN_REG1_out1,  // uint32
                                   Subsystem3_out1  // uint32
                                   );

  assign E_OUT = Subsystem3_out1;

  assign F_OUT = E_IN_REG_out1;

  assign G_OUT = F_IN_REG_out1;

  assign Constant1_out1 = 32'b10100100110011100001010010001011;



  assign ADD14_out1 = Constant1_out1 + W;



  assign H_OUT_1 = ADD14_out1;

endmodule  // Comp_2

