// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp1_20.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_20
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/Exp1_20
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_20
          (clk,
           In1,
           In2,
           In3,
           In4,
           Out1,
           Out2,
           Out3,
           Out4);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32


  reg [31:0] Delay2_out1;  // uint32
  reg [31:0] Delay1_out1;  // uint32

 latch u_latch_1(.clk(clk),.In(In3),.Out(Out3));
 latch u_latch_2(.clk(clk),.In(In4),.Out(Out4));


  assign Out1 = In1;

  assign Out2 = In2;

 
endmodule  // Exp1_20

