// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp1_56.v
// Created: 2022-08-02 16:52:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_56
// Source Path: sha_64_unroll/Hardware/SHA1/Expander1/Exp1_56
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_56
          (clk,
           In1,
           In2,
           In3,
           In4,
           In5,
           In6,
           In7,
           In8,
           In9,
           Out1,
           Out2,
           Out3,
           Out4,
           Out5,
           Out6,
           Out7,
           Out8,
           Out9);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  input   [31:0] In5;  // uint32
  input   [31:0] In6;  // uint32
  input   [31:0] In7;  // uint32
  input   [31:0] In8;  // uint32
  input   [31:0] In9;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32
  output  [31:0] Out5;  // uint32
  output  [31:0] Out6;  // uint32
  output  [31:0] Out7;  // uint32
  output  [31:0] Out8;  // uint32
  output  [31:0] Out9;  // uint32
 reg [31:0] Delay_out1;  // uint32

   parameter I1 =0 ;
 
if (I1 == 0) begin
latch u_latch_1(.clk(clk),.In(In1),.Out(Out1));
  end
 else begin
 	 latch_inv u_latch1 (.clk(clk),.In(In1),.Out(Out1));
 end 

 latch_inv u_latch2 (.clk(clk),.In(In2),.Out(Out2));
 latch_inv u_latch3 (.clk(clk),.In(In3),.Out(Out3));
 latch_inv u_latch4 (.clk(clk),.In(In4),.Out(Out4));
 latch_inv u_latch5 (.clk(clk),.In(In5),.Out(Out5));
 latch_inv u_latch6 (.clk(clk),.In(In6),.Out(Out6));
 latch_inv u_latch7 (.clk(clk),.In(In7),.Out(Out7));
 latch_inv u_latch8 (.clk(clk),.In(In8),.Out(Out8));
 latch_inv u_latch9 (.clk(clk),.In(In9),.Out(Out9));
 
  endmodule  // Exp1_56

