// -------------------------------------------------------------
// 
// File Name: hdlsrc/expander_power_opt/Exp1_18.v
// Created: 2022-08-12 14:04:03
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp1_18
// Source Path: expander_power_opt/Hardware/SHA1/Expander1/Exp1_18
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp1_18
          (clk,
           In1,
           In2,
           In3,
           In4,
           Out1,
           Out2,
           Out3,
           Out4);


  input   clk;
  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32

// wire [31:0] Nonce;


  assign Out1 = In1;

  
  wire [31:0] Delay2_out1;  // uint32


latch u_latch (.clk(clk),.In(In2),.Out(Delay2_out1));


  assign Out2 = Delay2_out1-9;


 // latch u_latch_1(.clk(clk),.In(In2),.Out(Nonce));

//   assign Out2 = Nonce - 9; 
 
   assign Out3 = In3;

  assign Out4 = In4;

endmodule  // Exp1_18

