// -------------------------------------------------------------
// 
// File Name: hdlsrc_hard/Sha2_trimmed/SC3.v
// Created: 2022-06-30 15:03:17
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SC3
// Source Path: Sha2_trimmed/Hardware/SHA1/Expander1/Exp1_21-22/SC3 
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SC3
          (In1,
           In2,
           Out1);


  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  output  [31:0] Out1;  // uint32


  wire [31:0] Bit_Rotate_out1;  // uint32
  wire [31:0] Bit_Rotate1_out1;  // uint32
  wire [31:0] Bit_Shift_out1;  // uint32
  wire [31:0] Bitwise_XOR_out1;  // uint32
  wire [31:0] Add_out1;  // uint32


  assign Bit_Rotate_out1 = {In2[16:0], In2[31:17]};



  assign Bit_Rotate1_out1 = {In2[18:0], In2[31:19]};



  assign Bit_Shift_out1 = In2 >> 8'd10;



  assign Bitwise_XOR_out1 = Bit_Shift_out1 ^ (Bit_Rotate_out1 ^ Bit_Rotate1_out1);



  assign Add_out1 = In1 + Bitwise_XOR_out1;



  assign Out1 = Add_out1;

endmodule  // SC3

