// -------------------------------------------------------------
// 
// File Name: hdlsrc_hard/Sha2_trimmed/Subsystem50.v
// Created: 2022-06-30 15:03:19
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem50
// Source Path: Sha2_trimmed/Hardware/SHA2/Expander2/Exp2_25-26/Subsystem50
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SC4
          (In1,
           In2,
           In3,
           Out1);


  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  output  [31:0] Out1;  // uint32


  wire [31:0] Bit_Rotate2_out1;  // uint32
  wire [31:0] Bit_Rotate3_out1;  // uint32
  wire [31:0] Bit_Shift1_out1;  // uint32
  wire [31:0] Bitwise_XOR_out1;  // uint32
  wire [31:0] Add_out1;  // uint32
  wire [31:0] Add1_out1;  // uint32


  assign Bit_Rotate2_out1 = {In1[16:0], In1[31:17]};



  assign Bit_Rotate3_out1 = {In1[18:0], In1[31:19]};



  assign Bit_Shift1_out1 = In1 >> 8'd10;



  assign Bitwise_XOR_out1 = Bit_Shift1_out1 ^ (Bit_Rotate2_out1 ^ Bit_Rotate3_out1);



  assign Add_out1 = In2 + Bitwise_XOR_out1;



  assign Add1_out1 = In3 + Add_out1;



  assign Out1 = Add1_out1;

endmodule  // Subsystem50

