// -------------------------------------------------------------
// 
// File Name: hdlsrc_comp/untitled/CH.v
// Created: 2022-06-22 14:04:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CH
// Source Path: untitled/Subsystem/COMPRESSOR2/Comp1/CH
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CH
          (X,
           Y,
           Z,
           OUT);


  input   [31:0] X;  // uint32
  input   [31:0] Y;  // uint32
  input   [31:0] Z;  // uint32
  output  [31:0] OUT;  // uint32


  wire [31:0] BITWISE_AND_X_Y_out1;  // uint32
  wire [31:0] BITWISE_NOT_X_out1;  // uint32
  wire [31:0] BITWISE_AND_X_Z_out1;  // uint32
  wire [31:0] BITWISE_XOR_out1;  // uint32

  // function out = ch( x, y, z )
  //    % Function maj : Performs CH operation.(§4.1.2)
  //    out = bitxor( x & y ,~x & z );
  // end


  assign BITWISE_AND_X_Y_out1 = X & Y;



  assign BITWISE_NOT_X_out1 =  ~ X;



  assign BITWISE_AND_X_Z_out1 = BITWISE_NOT_X_out1 & Z;



 // assign BITWISE_XOR_out1 = BITWISE_AND_X_Y_out1 ^ BITWISE_AND_X_Z_out1;
  assign BITWISE_XOR_out1 = BITWISE_AND_X_Y_out1 | BITWISE_AND_X_Z_out1;



  assign OUT = BITWISE_XOR_out1;

endmodule  // CH

