// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Exp2_1.v
// Created: 2022-08-02 16:53:01
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Exp2_1
// Source Path: sha_64_unroll/Hardware/SHA2/Expander2/Exp2_1
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Exp2_1
          (In1,
           In2,
           In3,
           In4,
           In5,
           In6,
           In7,
           In8,
           Out1,
           Out2,
           Out3,
           Out4,
           Out5,
           Out6,
           Out7,
           Out8);


  input   [31:0] In1;  // uint32
  input   [31:0] In2;  // uint32
  input   [31:0] In3;  // uint32
  input   [31:0] In4;  // uint32
  input   [31:0] In5;  // uint32
  input   [31:0] In6;  // uint32
  input   [31:0] In7;  // uint32
  input   [31:0] In8;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32
  output  [31:0] Out3;  // uint32
  output  [31:0] Out4;  // uint32
  output  [31:0] Out5;  // uint32
  output  [31:0] Out6;  // uint32
  output  [31:0] Out7;  // uint32
  output  [31:0] Out8;  // uint32




  assign Out1 = In1;

  assign Out2 = In2;

  assign Out3 = In3;

  assign Out4 = In4;

  assign Out5 = In5;

  assign Out6 = In6;

  assign Out7 = In7;

  assign Out8 = In8;

endmodule  // Exp2_1

