// -------------------------------------------------------------
// 
// File Name: hdlsrc_1/sha_64_unroll/Hardware.v
// Created: 2022-08-02 16:53:01
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.5
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Hardware
// Source Path: sha_64_unroll/Hardware
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Hardware
          (W1,
           W2,
           W3,nonce,
           H0,
           H1,
           H2,
           H3,
           H4,
           H5,
           H6,
           H7,
           Out1,
           Out2);


  input   [31:0] W1;  // uint32
  input   [31:0] W2;  // uint32
  input   [31:0] W3,nonce;  // uint32
  input   [31:0] H0;  // uint32
  input   [31:0] H1;  // uint32
  input   [31:0] H2;  // uint32
  input   [31:0] H3;  // uint32
  input   [31:0] H4;  // uint32
  input   [31:0] H5;  // uint32
  input   [31:0] H6;  // uint32
  input   [31:0] H7;  // uint32
  output  [31:0] Out1;  // uint32
  output  [31:0] Out2;  // uint32


  wire [31:0] SHA1_out1_0;  // uint32
  wire [31:0] SHA1_out1_1;  // uint32
  wire [31:0] SHA1_out1_2;  // uint32
  wire [31:0] SHA1_out1_3;  // uint32
  wire [31:0] SHA1_out1_4;  // uint32
  wire [31:0] SHA1_out1_5;  // uint32
  wire [31:0] SHA1_out1_6;  // uint32
  wire [31:0] SHA1_out1_7;  // uint32
  wire [31:0] SHA2_out1;  // uint32
  wire [31:0] SHA2_out2;  // uint32


  SHA1 u_SHA1 (.clk1(1'b0),
		.clk2(1'b0),
		.clk3(1'b0),
		.clk4(1'b0),
                .clkw_p1(1'b0),
                .clk_l(1'b0),
                .clkm_p1(1'b0),
		.reset(1'b0),
               .Input_rsvd(W1),  // uint32
               .Input1(W2),  // uint32
               .Input2(W3),  // uint32
               .nonce(nonce),
               .H0(H0),  // uint32
               .H1(H1),  // uint32
               .H2(H2),  // uint32
               .H3(H3),  // uint32
               .H4(H4),  // uint32
               .H5(H5),  // uint32
               .H6(H6),  // uint32
               .H7(H7),  // uint32
               .Out1_0(SHA1_out1_0),  // uint32
               .Out1_1(SHA1_out1_1),  // uint32
               .Out1_2(SHA1_out1_2),  // uint32
               .Out1_3(SHA1_out1_3),  // uint32
               .Out1_4(SHA1_out1_4),  // uint32
               .Out1_5(SHA1_out1_5),  // uint32
               .Out1_6(SHA1_out1_6),  // uint32
               .Out1_7(SHA1_out1_7)  // uint32
               );

  SHA2 u_SHA2 (.clk1(1'b0),
		.clk2(1'b0),
		.clk3(1'b0),
		.clk4(1'b0),
		.resetn(1'b0),
               .In1_0(SHA1_out1_0),  // uint32
               .In1_1(SHA1_out1_1),  // uint32
               .In1_2(SHA1_out1_2),  // uint32
               .In1_3(SHA1_out1_3),  // uint32
               .In1_4(SHA1_out1_4),  // uint32
               .In1_5(SHA1_out1_5),  // uint32
               .In1_6(SHA1_out1_6),  // uint32
               .In1_7(SHA1_out1_7),  // uint32
               .Out1(SHA2_out1),  // uint32
               .Out2(SHA2_out2)  // uint32
               );

  assign Out1 = ~SHA2_out1;

  assign Out2 = ~SHA2_out2;

endmodule  // Hardware

