// -------------------------------------------------------------
// 
// File Name: hdlsrc_comp/untitled/MAJ.v
// Created: 2022-06-22 14:04:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MAJ
// Source Path: untitled/Subsystem/COMPRESSOR2/Comp1/MAJ
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MAJ
          (X,
           Y,
           Z,
           OUT);


  input   [31:0] X;  // uint32
  input   [31:0] Y;  // uint32
  input   [31:0] Z;  // uint32
  output  [31:0] OUT;  // uint32


  wire [31:0] BITWISE_AND_X_Y_out1;  // uint32
  wire [31:0] BITWISE_AND_X_Z_out1;  // uint32
  wire [31:0] BITWISE_AND_Y_Z_out1;  // uint32
  wire [31:0] BITWISE_XOR_out1;  // uint32

  // function out = maj( x, y, z )
  //    % Function maj : Performs MAJ operation.(§4.1.2)
  //    out = bitxor( bitxor( x & y, x & z ) , y & z );
  // end


  assign BITWISE_AND_X_Y_out1 = X & Y;



  assign BITWISE_AND_X_Z_out1 = X & Z;



  assign BITWISE_AND_Y_Z_out1 = Y & Z;



  //assign BITWISE_XOR_out1 = BITWISE_AND_Y_Z_out1 ^ (BITWISE_AND_X_Y_out1 ^ BITWISE_AND_X_Z_out1);
  assign BITWISE_XOR_out1 = BITWISE_AND_Y_Z_out1 | (BITWISE_AND_X_Y_out1 | BITWISE_AND_X_Z_out1);



  assign OUT = BITWISE_XOR_out1;

endmodule  // MAJ

